# 指定一個基礎映像檔
FROM python:3.9-alpine

# 在容器內建立一個目錄
RUN mkdir /app

# 指定工作目錄為/app
WORKDIR /app

# 將本地端的檔案複製到容器內的/app目錄
COPY . /app

# 更新安裝套件
RUN apk update && apk add go RUN && \apt-get install -y gcc# 安裝 
pyserial 套件 RUN pip install pyserial
# RUN apk add py3-rpi.gpio
RUN pip install RPi.GPIO
# 執行 go 程式和python 程式
CMD go run main.go 
CMD python SEND_LOG_onPI.py 

# 對外暴露容器的 8080 port
EXPOSE 8080
