# 指定一個基礎映像檔
FROM python:3.9-alpine

# 在容器內建立一個目錄
RUN mkdir /app

# 指定工作目錄為/app
WORKDIR /app

# 將本地端的檔案複製到容器內的/app目錄
COPY . /app

# 更新安裝套件
RUN apk update && \
    apk add --no-cache build-base && \
    apk add --no-cache go && \
    pip install RPi.GPIO && \
    apk del build-base

# 安裝 pyserial 套件
RUN pip install pyserial
RUN pip install requests
RUN pip install RPi.GPIO

# 將要執行的命令寫在一個shell腳本文件中
COPY run.sh /app
RUN chmod +x /app/run.sh

# 設定執行多個命令
ENTRYPOINT ["/app/run.sh"]

# 對外暴露容器的 8080 port
EXPOSE 8080
